API/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from . import views
from social.views import *

router = routers.DefaultRouter()
router.register(r'users' , views.UserViewSet , base_name = 'user')
router.register(r'groups' , views.GroupViewSet)
router.register(r'leaveApplications' , views.LeaveApplicationViewSet)
router.register(r'myLeave' , views.selfSerializerLeaveManagementViewSet, base_name = 'myLeave')
router.register(r'userDesignation' , views.userDesignationViewSet , base_name = 'userdesignation')
router.register(r'notification' , views.notificationViewSet, base_name = 'notification')
router.register(r'chatMessage' , views.chatMessageViewSet, base_name = 'chatmessage')
router.register(r'chatMessageBetween' , views.chatMessageBetweenViewSet, base_name = 'chatbetween')
router.register(r'userProfile' , views.userProfileViewSet , base_name ='userprofile')
router.register(r'socialPost' , postViewSet , base_name ='post')
router.register(r'socialPicture' , pictureViewSet , base_name ='picture')
router.register(r'socialAlbum' , albumViewSet , base_name ='album')
router.register(r'socialPostComment' , postCommentsViewSet , base_name ='postcomment')
router.register(r'socialPostLike' , postLikesViewSet , base_name ='postlike')
router.register(r'socialCommentLike' , commentLikesViewSet , base_name ='commentlike')
router.register(r'socialPictureComment' , pictureCommentsViewSet , base_name ='picturecomment')
router.register(r'socialPictureLike' , pictureLikesViewSet , base_name ='picturelike')

urlpatterns = [
    url(r'^', include(router.urls)),
]

Employee/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [

    url(r'^admin/', 'HR.views.admin', name='admin'),
    url(r'^home/', views.home, name='home'),
    url(r'^support/', views.support, name='support'),
    url(r'^payroll/', views.payroll, name='payroll'),
    url(r'^team/', views.team, name='team'),
    url(r'^learn/', views.learn, name='learn'),
    url(r'^business/', views.business, name='business'),
    url(r'^document/', views.document, name='document'),
    url(r'^project/', 'projectManagement.views.project', name='project'),
    url(r'^recruit/', views.recruit, name='recruit'),
]

libreERP/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^api/', include('API.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^HR/', include('Employee.urls' , namespace = 'HR')),
    url(r'^test/', 'Employee.views.test', name='test'),
    url(r'^login/', 'Employee.views.Login' , name ='login'),
    url(r'^logout/', 'Employee.views.Logout' , name ='logout'),
    url(r'^api-auth/', include('rest_framework.urls', namespace ='rest_framework')),
    # url('^', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

libreERP/templates/admin.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<div class="container-fluid "  >

  <div class="row">
    <div class="panel-group col-md-2 col-sm-12 nav-sidebarAccordion" id="accordion">
      <!-- <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          <div class="panel-title" align="left"><i class="fa fa-check-square-o"></i>&nbsp;&nbsp;Approvals</div>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
          <div class="panel-body">
            <ul class="nav" >
              <li><a href="#id0">Inbound <span class="label label-success pull-right">$ 320</span></a> </li>
              <li><a href="#id1">Submitted</a></li>
              <li><a href="#id2">Create new</a></li>
              <li><a href="#id3">Approved</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          <div class="panel-title" align="left"><i class="fa fa-diamond"></i>&nbsp;&nbsp;Assets</div>
        </div>
        <div id="collapseThree" class='panel-collapse collapse'>
          <div class="panel-body">
            <ul class="nav" >
              <li><a href="#id0">New arrival <span class="label label-success">$ 320</span></a> </li>
              <li><a href="#id1"><i class="fa fa-shopping-cart"></i>&nbsp;&nbsp;New requirements</a></li>
              <li><a href="#id2">Issue</a></li>
              <li><a href="#id3">Return / Change</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          <div class="panel-title" align="left"><i class="fa fa-pie-chart"></i>&nbsp;&nbsp;Reports</div>
        </div>
        <div id="collapseFour" class="panel-collapse collapse ">
          <div class="panel-body">
            <ul class="nav" >
              <li><a href="#id0">New &nbsp;&nbsp;<span class="label label-success">320</span></a> </li>
              <li><a href="#id1">Incomplete</a></li>
              <li><a href="#id2">Current</a></li>
              <li><a href="#id3">Archive</a></li>
            </ul>
          </div>
        </div>
      </div> -->
      <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
          <div class="panel-title" align="left"><i class="fa fa-users"></i>&nbsp;&nbsp;Employees</div>
        </div>
        <div id="collapseFive" class="panel-collapse collapse {% ifequal 'employees' navContext %} in {% endifequal %}">
          <div class="panel-body">
            <ul class="nav" >
              <li><a href="{% url 'HR:admin' %}?action=searchEmp"><i class="fa fa-search"></i> Seach</a> </li>
              <li><a href="{% url 'HR:admin' %}?module=leaveManagement"><i class="fa fa-calendar"></i> Leave management</a></li>
              <li><a href="{% url 'HR:admin' %}?action=createUser"><i class="fa fa-user-plus"></i> Mannual entry</a></li>
              <!-- <li><a href="#id2"><i class="fa fa-user-times"></i> Off boarding</a></li> -->
            </ul>
          </div>
        </div>
      </div>
      <!-- <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
          <div class="panel-title" align="left"><i class="fa fa-credit-card"></i>&nbsp;&nbsp;Finance</div>
        </div>
        <div id="collapseSix" class="panel-collapse collapse">
          <div class="panel-body">
            <ul class="nav" >
              <li><a  href="#id2">Search</a></li>
              <li><a  href="#id0">Inbound</a> </li>
              <li><a  href="#id1">Pending</a></li>
              <li><a  href="#id1">Bills received</a></li>
              <li><a  href="#id2">Auditing</a></li>
              <li><a  href="#id2">Statistics</a></li>
              <li><a  href="#id2">Analytics</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">
          <div class="panel-title" align="left"><i class="fa fa-briefcase"></i>&nbsp;&nbsp;Corporate</div>
        </div>
        <div id="collapseSeven" class="panel-collapse collapse">
          <div class="panel-body">
            <ul class="nav" >
              <li><a  href="#id2">Book appointments</a></li>
              <li><a  href="#id0"><i class="fa fa-calendar"></i>&nbsp;&nbsp;New meeting</a> </li>
              <li><a  href="#id1">MOM</a></li>
              <li><a  href="#id1"><i class="fa fa-glass"></i>&nbsp;&nbsp;Events</a></li>
              <li><a  href="#id2">Add/Update rules</a></li>
              <li><a  href="#id2">Rules and Regulations</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseEight">
          <div class="panel-title" align="left"><i class="fa fa-gavel"></i>&nbsp;&nbsp;Legal</div>
        </div>
        <div id="collapseEight" class="panel-collapse collapse">
          <div class="panel-body">
            <ul class="nav" >
              <li><a  href="#id2">Consult</a></li>
              <li><a  href="#id0">Ongoing&nbsp;&nbsp;<span class="label label-success">16</span></a> </li>
              <li><a  href="#id1">Approval received</a></li>
              <li><a  href="#id1">New</a></li>
              <li><a  href="#id2">Archive</a></li>
            </ul>
          </div>
        </div>
      </div> -->
    </div>
    <div class="col-md-10 col-md-offset-2">
      <!-- <div class="row"> -->

        {% block adminContent %}
        {% if messages %}
          {% for message in messages %}

            <div class="alert alert-{% if 'error'  in message.tags %}danger{% else %}{{message.tags}}{% endif %}">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% endblock %}
      <!-- </div> -->

    </div>
  </div>
</div>
{% endblock %}
{% block specific_js %}
<script src="{% static 'js/ngSearchEmp.js' %}"></script>
<script src="{% static 'js/ngCalendar.js' %}"></script>
<script type="text/javascript">

  $(document).ready(function() {
    // alert("going to load");
    angular.bootstrap( document.getElementById('searchEmpApp'), ['genericSearch']);
  });
</script>

{% endblock %}

libreERP/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index - Employee</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/angular-aside.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/header.css' %}" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" charset="utf-8">
    {% block specific_css %}{% endblock %}
  </head>
  <body>

    <div style="margin-bottom:70px;">
      {% block header %}{% endblock %}
    </div>
    {% block content %}{% endblock %}
    <div id="instantMessanger">
      <div id="instantMessangerCtrl" ng-controller="myCtrl">
        {% verbatim %}
        <div ng-repeat="friend in imWindows">
          <chat-window friend-url="friend.url" pos="$index" id="chatWindow{{friend.username}}" cancel="closeIMWindow($index)"></chat-window>
        </div>
        {% endverbatim %}
      </div>
    </div>
    {% block footer %}{% endblock %}

    {% include 'footer.html' %}
    <script type="text/javascript">
      var wampBindName = "{{user.username}}";
    </script>
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/angular.min.js' %}"></script>
    <script src="{% static 'js/angular-sanitize.min.js' %}"></script>
    <script src="{% static 'js/ui-bootstrap-tpls-0.13.4.min.js' %}"></script>
    <script src="{% static 'js/angular-aside.js' %}"></script>
    <script src="{% static 'js/autobahn.min.js' %}"></script>
    <script src="{% static 'js/libreHRDirectives.js' %}"></script>
    <script src="{% static 'js/instantMessanger.js' %}"></script>
    <script src="{% static 'js/ngNavBarControls.js' %}"></script>
    <script src="{% static 'js/genericSearchTable.js' %}"></script>

    <script type="text/javascript">
      $(document).ready(function() {
        angular.bootstrap( document.getElementById('notificationAppDiv'), ['notificationApp']);
        angular.bootstrap( document.getElementById('instantMessanger'), ['instantMessanger']);
      });
    </script>
    <script src="{% static 'js/wampProcessors.js' %}"></script>
    {% block specific_js %}{% endblock %}
  </body>
</html>

libreERP/templates/businessManagement.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<h1> Hello user {% ifequal request.path '/HR/home/' %} Hey {% endifequal %}</h1>

{% endblock %}

{% block footer %}
  Footer
{% endblock %}

libreERP/templates/documentManagement.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<h1> Hello user {% ifequal request.path '/HR/home/' %} Hey {% endifequal %}</h1>

{% endblock %}

{% block footer %}
  Footer
{% endblock %}

libreERP/templates/footer.html
<footer class="footer" >
	<div class="container pull-right" style="padding:50px;">
		<p align="right" class="text-muted">&copy; Brand 2015.</p>
	</div>
</footer>

libreERP/templates/headerHR.html
{% load staticfiles %}
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navBar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        Brand <i class="fa fa-angle-right"></i>
      </a>
      <div class="navbar-brand" >HR</div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navBar">

  		<ul class="nav navbar-nav">
  			<li class="{% if '/HR/home/' in request.path %} active {% endif %}"><a href="{% url 'HR:home' %}"><i class="fa fa-home"></i>&nbsp;&nbsp;Home</a></li>
  			<li class="{% if '/HR/admin/' in request.path %} active {% endif %}"><a href="{% url 'HR:admin' %}"><i class="fa fa-user"></i>&nbsp;&nbsp;Admin</a></li>
  			<!-- <li class="{% if '/HR/support/' in request.path %} active {% endif %}"><a href="{% url 'HR:support' %}"><i class="fa fa-phone"></i>&nbsp;&nbsp;Support</a></li>
  			<li class="{% if '/HR/payroll/' in request.path %} active {% endif %}"><a href="{% url 'HR:payroll' %}"><i class="fa fa-money"></i>&nbsp;&nbsp;Payroll</a></li>
  			<li class="{% if '/HR/team/' in request.path %} active {% endif %}"><a href="{% url 'HR:team' %}"><i class="fa fa-users"></i>&nbsp;&nbsp;TM</a></li>
  			<li class="{% if '/HR/learn/' in request.path %} active {% endif %}"><a href="{% url 'HR:learn' %}"><i class="fa fa-book"></i>&nbsp;&nbsp;LM</a></li>
  			<li class="{% if '/HR/business/' in request.path %} active {% endif %}"><a href="{% url 'HR:business' %}"><i class="fa fa-building-o"></i>&nbsp;&nbsp;BM</a></li>
  			<li class="{% if '/HR/document/' in request.path %} active {% endif %}"><a href="{% url 'HR:document' %}"><i class="fa fa-file-text-o"></i>&nbsp;&nbsp;DM</a></li> -->
        <!-- <li class="{% if '/HR/project/' in request.path %} active {% endif %}"><a href="{% url 'HR:project' %}"><i class="fa fa-flask"></i>&nbsp;&nbsp;PM</a></li> -->
  			<!-- <li class="{% if '/HR/recruit/' in request.path %} active {% endif %}"><a href="{% url 'HR:recruit' %}"><i class="fa fa-graduation-cap"></i>&nbsp;&nbsp;Recruit</a></li> -->
  		</ul>

      <div id="notificationAppDiv">
        <div id="headerNotificationCtrl" ng-controller="myCtrl">
          <form class="navbar-form navbar-right" role="search">
            <input type="text" class="form-control" placeholder="" style="width:300px">
          </form>
      		<ul class="nav navbar-nav navbar-right">
      			<li class="dropdown">
      			  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.get_full_name |title}} &nbsp;<span class="glyphicon glyphicon-chevron-down"></span></a>
      			  <ul class="dropdown-menu">
        				<li><img class="img-responsive" width="200px" alt="profile-pic" src="{{MEDIA_URL}}/{{user.profile.displayPicture}}" style="top:-5px; position:relative; width:200px"></li>
        				<li><div style="text-align:center; -moz-user-select: none;"> {{user.email}}</br><small>(HR Associate)</small></div></li>
        				<li role="separator" class="divider"></li>
        				<li><a href="{% url 'HR:admin' %}?action=profileSettings"><i class="fa fa-gears"></i>&nbsp;&nbsp;Settings</a></li>
                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i>&nbsp;&nbsp;Logout</a></li>
        				<li role="separator" class="divider"></li>
        				<li><a href="#"><i class="fa fa-question"></i>&nbsp;&nbsp;&nbsp;Help</a></li>
        				<li><a href="#">&nbsp;<i class="fa fa-info"></i>&nbsp;&nbsp;&nbsp;About</a></li>
      			  </ul>
      			</li>
      		</ul>
          {% verbatim %}
          <ul class = "nav navbar-nav navbar-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" style="width:55px" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-envelope-o fa-lg"></i><span class="label label-success" style="position: absolute;top: 5px;">{{imsCount}}</span></a>
              <ul class="dropdown-menu navDropDownList">
                <li>
                  <!-- inner menu: contains the actual data -->
                  <ul class="nav" style="position:relative; top:-5px;">
                    <div ng-repeat="message in ims">
                    <message-strip data = "message" open-chat="openChatWindow(message.originator)"></message-strip>
                    </div>
                  </ul>
                </li>
                <a href="#"><i class = "fa fa-external-link"></i> See All Messages</a>
              </ul>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" style="width:55px" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-flag-o fa-lg"></i><span class="label label-warning" style="position: absolute;top: 5px;">{{notificationCount}}</span></a>
              <ul class="dropdown-menu navDropDownList">
                <li>
                  <!-- inner menu: contains the actual data -->
                  <ul class="nav" style="position:relative; top:-5px;">
                    <div ng-repeat="notice in notifications">

                      <notification-strip data = "notice" ></notification-strip>
                    </div>
                  </ul>
                </li>
                <a href="#"><i class = "fa fa-external-link"></i> See All Notifications</a>
              </ul>
            </li>
          </ul> <!-- /. notification icons group -->

          {% endverbatim %}
        </div> <!-- /. Controller -->
      </div> <!-- /ng application -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

libreERP/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<!-- <h1> Hello user {% ifequal request.path '/HR/home/' %} Hey {% endifequal %}</h1>
Pradeep
<img src="{{MEDIA_URL}}images/avatar3.png" alt="" /> -->
<div class="col-sm-1" id="">
  <ul class="nav nav-sidebarDashboard" >
    <li><a data-toggle="tab" href="#dash"><div align="center">&nbsp;<i class="fa fa-home fa-3x"></i></div></a></li>
    <li><a data-toggle="tab" href="#mail"><div align="center"><i class="fa fa-envelope-o fa-3x"></i></div></a></li>
    <li><a data-toggle="tab" href="#social"><div align="center">&nbsp;&nbsp;&nbsp;<i class="fa fa-facebook fa-3x"></i></div></a></li>
    <li><a data-toggle="tab" href="#forums"><div align="center"><i class="fa fa-newspaper-o fa-3x"></i></div></a></li>
    <li><a data-toggle="tab" href="#calender"><div align="center">&nbsp;<i class="fa fa-calendar fa-3x"></i></div></a></li>
    <li><a data-toggle="tab" href="#notes"><div align="center">&nbsp;<i class="fa fa-sticky-note-o fa-3x"></i></i></div></a></li>
  </ul>
</div>

<div class="tab-content col-sm-11">
  <div id="dash" class="tab-pane fade">
    {% include 'dashboardHome.html' %}
  </div>
  <div id="mail" class="tab-pane fade">
    {% include 'dashboardMail.html' %}
  </div>
  <div id="im" class="tab-pane fade">
    {% include 'dashboardIM.html' %}
  </div>
  <div id="social" class="tab-pane fade">
    {% include 'dashboardSocial.html' %}
  </div>
  <div id="forums" class="tab-pane fade">
    {% include 'dashboardForums.html' %}
  </div>
  <div id="calender" class="tab-pane fade">
    {% include 'dashboardCalendar.html' %}
  </div>
  <div id="notes" class="tab-pane fade">
    {% include 'dashboardNotes.html' %}
  </div>
</div>
{% endblock %}

{% block specific_js %}
<script src="{% static 'js/ngSocial.js' %}"></script>
<script src="{% static 'js/ngDraggable.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function() {
    angular.bootstrap( document.getElementById('socialAppDiv'), ['social']);
  });
</script>
{% endblock %}

libreERP/templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index - Employee</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/datepicker.css' %}" media="screen" charset="utf-8">

  </head>
  <body>
    <div class="container">
      <h1>Index page - Employee</h1>
      <img src="{% static 'images/sample_image.jpeg' %}" alt="My image"/>

      <a href="{% url 'login' %}" class="btn btn-danger" role="button">Login</a>
    </div> <!-- /container -->

    <input type="text" class="form-control" >
    <input type="text" class="form-control" >

    <script src="{% static 'js/jquery-2.1.4.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

    <script type="text/javascript">
      $(document).ready(function() {
        $('.datepicker').datepicker({
          format: 'yyyy-mm-dd',
        });
      });
    </script>

  </body>
</html>

libreERP/templates/learningManagement.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<h1> Hello user {% ifequal request.path '/HR/home/' %} Hey {% endifequal %}</h1>

{% endblock %}

{% block footer %}
  Footer
{% endblock %}

libreERP/templates/payroll.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<h1> Hello user {% ifequal request.path '/HR/payroll/' %} Hey {% endifequal %}</h1>

{% endblock %}

{% block footer %}
  Footer
{% endblock %}

libreERP/templates/recruit.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<h1> Hello user {% ifequal request.path '/HR/home/' %} Hey {% endifequal %}</h1>

{% endblock %}

{% block specific_js %}

<script src="{% static 'js/autobahn.min.js' %}"></script>
<script type="text/javascript">

   // the URL of the WAMP Router (Crossbar.io)
   //
  var wsuri;
  wsuri = "ws://10.140.7.94:8080/ws";

  var connection = new autobahn.Connection({
    url: wsuri,
    realm: "realm1"
  });


   // timers
   //
   var t1, t2;


   // fired when connection is established and session attached
   //
   connection.onopen = function (session, details) {

      console.log("Connected");

      // SUBSCRIBE to a topic and receive events
      //
      function onhello (args) {
         var msg = args[0];
         console.log("event for 'onhello' received: " + msg);
      }
      session.subscribe('com.example.onhello', onhello).then(
         function (sub) {
            console.log("subscribed to topic 'onhello'");
         },
         function (err) {
            console.log("failed to subscribed: " + err);
         }
      );


      // REGISTER a procedure for remote calling
      //
      function add2 (args) {
         var x = args[0];
         var y = args[1];
         console.log("add2() called with " + x + " and " + y);
         return x + y;
      }
      session.register('com.example.add2', add2).then(
         function (reg) {
            console.log("procedure add2() registered");
         },
         function (err) {
            console.log("failed to register procedure: " + err);
         }
      );


      // PUBLISH and CALL every second .. forever
      //
      // var counter = 0;
      // setInterval(function () {
      //
      //    // PUBLISH an event
      //    //
      //    session.publish('com.example.oncounter', [counter]);
      //    console.log("published to 'oncounter' with counter " + counter);
      //
      //    // CALL a remote procedure
      //    //
      //    session.call('com.example.mul2', [counter, 3]).then(
      //       function (res) {
      //          console.log("mul2() called with result: " + res);
      //       },
      //       function (err) {
      //          if (err.error !== 'wamp.error.no_such_procedure') {
      //             console.log('call of mul2() failed: ' + err);
      //          }
      //       }
      //    );
      //
      //    counter += 1;
      // }, 100000000000000000);
   };


   // fired when connection was lost (or could not be established)
   //
   connection.onclose = function (reason, details) {
      console.log("Connection lost: " + reason);
      if (t1) {
         clearInterval(t1);
         t1 = null;
      }
      if (t2) {
         clearInterval(t2);
         t2 = null;
      }
   }


   // now actually open the connection
   //
   connection.open();

</script>

{% endblock %}

libreERP/templates/support.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<h1> Hello user {% ifequal request.path '/HR/support/' %} Hey {% endifequal %}</h1>

{% endblock %}

{% block footer %}
  Footer
{% endblock %}

libreERP/templates/teamManagement.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
  {% include 'headerHR.html' %}
{% endblock %}

{% block content %}
<h1> Hello user {% ifequal request.path '/HR/home/' %} Hey {% endifequal %}</h1>

{% endblock %}

{% block footer %}
  Footer
{% endblock %}